/* tslint:disable */
/* eslint-disable */
/**
 * nookpost-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base'
// @ts-ignore
import type { UserSettingsData } from '../models'
/**
 * UsersSettingsApi - axios parameter creator
 * @export
 */
export const UsersSettingsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Gets the user\'s settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userMeSettingsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/user/me/settings`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer required
      await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Updates the user\'s settings
     * @param {UserSettingsData} userSettingsData
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userMeSettingsPut: async (
      userSettingsData: UserSettingsData,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'userSettingsData' is not null or undefined
      assertParamExists('userMeSettingsPut', 'userSettingsData', userSettingsData)
      const localVarPath = `/user/me/settings`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer required
      await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        userSettingsData,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * UsersSettingsApi - functional programming interface
 * @export
 */
export const UsersSettingsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = UsersSettingsApiAxiosParamCreator(configuration)
  return {
    /**
     *
     * @summary Gets the user\'s settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async userMeSettingsGet(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserSettingsData>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.userMeSettingsGet(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['UsersSettingsApi.userMeSettingsGet']?.[localVarOperationServerIndex]
          ?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Updates the user\'s settings
     * @param {UserSettingsData} userSettingsData
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async userMeSettingsPut(
      userSettingsData: UserSettingsData,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.userMeSettingsPut(
        userSettingsData,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['UsersSettingsApi.userMeSettingsPut']?.[localVarOperationServerIndex]
          ?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * UsersSettingsApi - factory interface
 * @export
 */
export const UsersSettingsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = UsersSettingsApiFp(configuration)
  return {
    /**
     *
     * @summary Gets the user\'s settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userMeSettingsGet(options?: RawAxiosRequestConfig): AxiosPromise<UserSettingsData> {
      return localVarFp.userMeSettingsGet(options).then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Updates the user\'s settings
     * @param {UserSettingsData} userSettingsData
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userMeSettingsPut(
      userSettingsData: UserSettingsData,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .userMeSettingsPut(userSettingsData, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * UsersSettingsApi - object-oriented interface
 * @export
 * @class UsersSettingsApi
 * @extends {BaseAPI}
 */
export class UsersSettingsApi extends BaseAPI {
  /**
   *
   * @summary Gets the user\'s settings
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsersSettingsApi
   */
  public userMeSettingsGet(options?: RawAxiosRequestConfig) {
    return UsersSettingsApiFp(this.configuration)
      .userMeSettingsGet(options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Updates the user\'s settings
   * @param {UserSettingsData} userSettingsData
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsersSettingsApi
   */
  public userMeSettingsPut(userSettingsData: UserSettingsData, options?: RawAxiosRequestConfig) {
    return UsersSettingsApiFp(this.configuration)
      .userMeSettingsPut(userSettingsData, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
