/* tslint:disable */
/* eslint-disable */
/**
 * nookpost-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents a token object in the response to a Login request
 * @export
 * @interface AuthenticationLoginResponseBody
 */
export interface AuthenticationLoginResponseBody {
    /**
     * The token that can be used for authentication.
     * @type {string}
     * @memberof AuthenticationLoginResponseBody
     */
    'token'?: string | null;
    /**
     * The time in seconds the token expires on.
     * @type {number}
     * @memberof AuthenticationLoginResponseBody
     */
    'expiryTimestamp'?: number;
}

