/* tslint:disable */
/* eslint-disable */
/**
 * nookpost-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The body of a login request.
 * @export
 * @interface AuthenticationLoginRequestBody
 */
export interface AuthenticationLoginRequestBody {
    /**
     * The name of the user to log in.
     * @type {string}
     * @memberof AuthenticationLoginRequestBody
     */
    'username'?: string | null;
    /**
     * The users password
     * @type {string}
     * @memberof AuthenticationLoginRequestBody
     */
    'password'?: string | null;
}

