/* tslint:disable */
/* eslint-disable */
/**
 * nookpost-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CategoryData
 */
export interface CategoryData {
  /**
   * Name of the category
   * @type {string}
   * @memberof CategoryData
   */
  name?: string | null
  /**
   * Icon of the category
   * @type {string}
   * @memberof CategoryData
   */
  icon?: string | null
}
