/* tslint:disable */
/* eslint-disable */
/**
 * nookpost-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetAllCategoriesCategory } from './get-all-categories-category'

/**
 * The body of a Get request to category/all
 * @export
 * @interface GetAllCategoriesResponseBody
 */
export interface GetAllCategoriesResponseBody {
  /**
   * The currently present categories
   * @type {Array<GetAllCategoriesCategory>}
   * @memberof GetAllCategoriesResponseBody
   */
  categories?: Array<GetAllCategoriesCategory> | null
}
