/* tslint:disable */
/* eslint-disable */
/**
 * nookpost-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response to a post get request
 * @export
 * @interface GetPostResponseBody
 */
export interface GetPostResponseBody {
  /**
   * Title of the post
   * @type {string}
   * @memberof GetPostResponseBody
   */
  title?: string | null
  /**
   * Body/content of the post
   * @type {string}
   * @memberof GetPostResponseBody
   */
  body?: string | null
  /**
   * The banner image of the post
   * @type {string}
   * @memberof GetPostResponseBody
   */
  bannerImageBase64?: string | null
  /**
   * UUID of the category of the post
   * @type {string}
   * @memberof GetPostResponseBody
   */
  categoryUuid?: string | null
  /**
   * The display name of the author
   * @type {string}
   * @memberof GetPostResponseBody
   */
  authorDisplayName?: string | null
  /**
   * The UUID of the post.
   * @type {string}
   * @memberof GetPostResponseBody
   */
  uuid?: string | null
  /**
   * The username of the author
   * @type {string}
   * @memberof GetPostResponseBody
   */
  authorUsername?: string | null
  /**
   * Timestamp for the last modification of the post
   * @type {number}
   * @memberof GetPostResponseBody
   */
  modifiedOn?: number
  /**
   * Timestamp for the creation of the post
   * @type {number}
   * @memberof GetPostResponseBody
   */
  createdOn?: number
}
