/* tslint:disable */
/* eslint-disable */
/**
 * nookpost-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetAllCategoriesCategory
 */
export interface GetAllCategoriesCategory {
    /**
     * Name of the category
     * @type {string}
     * @memberof GetAllCategoriesCategory
     */
    'name'?: string | null;
    /**
     * Icon of the category
     * @type {string}
     * @memberof GetAllCategoriesCategory
     */
    'icon'?: string | null;
    /**
     * UUID of the category object
     * @type {string}
     * @memberof GetAllCategoriesCategory
     */
    'uuid'?: string | null;
}

