/* tslint:disable */
/* eslint-disable */
/**
 * nookpost-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetPostFilteredPost } from './get-post-filtered-post';

/**
 * The response to a get posts request with filter
 * @export
 * @interface GetPostFilteredResponseBody
 */
export interface GetPostFilteredResponseBody {
    /**
     * The posts remaining after the filter operation
     * @type {Array<GetPostFilteredPost>}
     * @memberof GetPostFilteredResponseBody
     */
    'posts'?: Array<GetPostFilteredPost> | null;
    /**
     * The total number of pages there are.
     * @type {number}
     * @memberof GetPostFilteredResponseBody
     */
    'totalNumberOfPages'?: number;
}

