/* tslint:disable */
/* eslint-disable */
/**
 * nookpost-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response to a post get request
 * @export
 * @interface PutPostRequestBody
 */
export interface PutPostRequestBody {
    /**
     * Title of the post
     * @type {string}
     * @memberof PutPostRequestBody
     */
    'title'?: string | null;
    /**
     * Body/content of the post
     * @type {string}
     * @memberof PutPostRequestBody
     */
    'body'?: string | null;
    /**
     * UUID of the category of the post
     * @type {string}
     * @memberof PutPostRequestBody
     */
    'categoryUuid'?: string | null;
    /**
     * The UUID of the post.
     * @type {string}
     * @memberof PutPostRequestBody
     */
    'uuid'?: string | null;
}

