/* tslint:disable */
/* eslint-disable */
/**
 * nookpost-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents the request body of a change password request
 * @export
 * @interface PutChangePasswordRequestBody
 */
export interface PutChangePasswordRequestBody {
  /**
   * The old password of the user
   * @type {string}
   * @memberof PutChangePasswordRequestBody
   */
  oldPassword?: string | null
  /**
   * The new password of the user
   * @type {string}
   * @memberof PutChangePasswordRequestBody
   */
  newPassword?: string | null
}
