/* tslint:disable */
/* eslint-disable */
/**
 * nookpost-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request body of a user put request
 * @export
 * @interface UserPutRequestBody
 */
export interface UserPutRequestBody {
  /**
   * The username of the user.
   * @type {string}
   * @memberof UserPutRequestBody
   */
  username?: string | null
  /**
   * User display name
   * @type {string}
   * @memberof UserPutRequestBody
   */
  displayName?: string | null
  /**
   * User Tagline/Status
   * @type {string}
   * @memberof UserPutRequestBody
   */
  tagLine?: string | null
  /**
   * User Bio
   * @type {string}
   * @memberof UserPutRequestBody
   */
  bio?: string | null
  /**
   * Profile picture of the user encoded as b64
   * @type {string}
   * @memberof UserPutRequestBody
   */
  profilePictureBase64?: string | null
  /**
   * Email of the user (null if user does not provide contact info)
   * @type {string}
   * @memberof UserPutRequestBody
   */
  email?: string | null
}
