/* tslint:disable */
/* eslint-disable */
/**
 * nookpost-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The response to a user get request if successful
 * @export
 * @interface UsersGetResponseBody
 */
export interface UsersGetResponseBody {
    /**
     * The username of the user.
     * @type {string}
     * @memberof UsersGetResponseBody
     */
    'username'?: string | null;
    /**
     * User display name
     * @type {string}
     * @memberof UsersGetResponseBody
     */
    'displayName'?: string | null;
    /**
     * User Tagline/Status
     * @type {string}
     * @memberof UsersGetResponseBody
     */
    'tagLine'?: string | null;
    /**
     * User Bio
     * @type {string}
     * @memberof UsersGetResponseBody
     */
    'bio'?: string | null;
    /**
     * Profile picture of the user encoded as b64
     * @type {string}
     * @memberof UsersGetResponseBody
     */
    'profilePictureBase64'?: string | null;
    /**
     * Email of the user (null if user does not provide contact info)
     * @type {string}
     * @memberof UsersGetResponseBody
     */
    'email'?: string | null;
}

