/* tslint:disable */
/* eslint-disable */
/**
 * nookpost-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents user settings objects
 * @export
 * @interface UserSettingsData
 */
export interface UserSettingsData {
  /**
   * Whether to use dark mode for the user
   * @type {boolean}
   * @memberof UserSettingsData
   */
  useDarkMode?: boolean | null
  /**
   * Whether to display the user\'s email on the profile page
   * @type {boolean}
   * @memberof UserSettingsData
   */
  displayEmailOnProfile?: boolean
}
